openapi: 3.0.0
info:
  title: Vehicle API
  version: 1.0.0
paths:
  /vehicles:
    get:
      summary: Get list of all vehicles
      responses:
        '200':
          description: A list of vehicles
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/Car'
                    - $ref: '#/components/schemas/Truck'
    post:
      summary: Add a new vehicle
      requestBody:
        description: Vehicle to add
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Car'
                - $ref: '#/components/schemas/Truck'
      responses:
        '201':
          description: Vehicle created

  /vehicles/{id}:
    delete:
      summary: Delete a vehicle by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Vehicle deleted
        '404':
          description: Vehicle not found

  /cars:
    post:
      summary: Add a new car
      requestBody:
        description: Car to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '201':
          description: Car created

  /trucks:
    post:
      summary: Add a new truck
      requestBody:
        description: Truck to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Truck'
      responses:
        '201':
          description: Truck created

components:
  schemas:
    Vehicle:
      type: object
      properties:
        id:
          type: string
          format: uuid
        brand:
          type: string
        model:
          type: string
      required:
        - id
        - brand
        - model

    Car:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
        - type: object
          properties:
            numberOfDoors:
              type: integer
              minimum: 2
              maximum: 5
          required:
            - numberOfDoors

    Truck:
      allOf:
        - $ref: '#/components/schemas/Vehicle'
        - type: object
          properties:
            loadCapacity:
              type: integer
              description: Load capacity in kilograms
            numberOfAxles:
              type: integer
          required:
            - loadCapacity
            - numberOfAxles